#ifndef MOTIONERRORTYPE_H
#define MOTIONERRORTYPE_H

#define MOTION_ERROR_KINEMATICSINVERSE_FAILED_TYPE					0x100
#define MOTION_ERROR_CANNOT_MOVE_WITHOUT_ENABLE_TYPE			0x110
#define MOTION_ERROR_CANNOT_MOVE_WHEN_STILL_MOVING_TYPE		0x120
#define MOTION_ERROR_CANNOT_ADD_JOINT_MOVE_TOTP_TYPE			0x130
#define MOTION_ERROR_CANNOT_ADD_LINEAR_MOVE_TOTP_TYPE			0x140
#define MOTION_ERROR_CANNOT_ADD_CIRCULAR_MOVE_TOTP_TYPE		0x141
#define MOTION_ERROR_UNKOWN_COORINATE_TYPE						0x150
#define MOTION_ERROR_INPUT_ENABLE_VALUE_ERROR_TYPE				0x160
#define MOTION_ERROR_INPUT_OUTOF_SOFT_LIMIT_TYPE					0x170
#define MOTION_ERROR_OUTPUT_OUTOF_SOFT_LIMIT_TYPE				0x180

#define MOTION_ERROR_COMMAND_BUFFER_FULL_TYPE						0x200


#define MOTION_ERROR_SINGLE_AXIS_MOVE_VELOCITY_OFR_TYPE			0x310
#define MOTION_ERROR_SINGLE_AXIS_MOVE_AXIS_OFR_TYPE				0x311
#define MOTION_ERROR_SINGLE_AXIS_MOVE_DIR_ERROR_TYPE				0x312

#define MOTION_ERROR_JOINT_MOVE_VELOCITY_ERROR_TYPE				0x320
#define MOTION_ERROR_JOINT_MOVE_ACC_ERROR_TYPE					0x321
#define MOTION_ERROR_JOINT_MOVE_DEC_ERROR_TYPE					0x322

#define MOTION_ERROR_LINEAR_VELOCITY_OFR_TYPE						0x330
#define MOTION_ERROR_ROTATION_VELOCITY_OFR_TYPE					0x331
#define MOTION_ERROR_LINEAR_MOVE_ACC_ERROR_TYPE					0x332
#define MOTION_ERROR_LINEAR_MOVE_DEC_ERROR_TYPE					0x333

#define MOTION_ERROR_CIRCULAR_VELOCITY_OFR_TYPE					0x340
#define MOTION_ERROR_CIRCULAR_ROTATION_VELOCITY_OFR_TYPE		0x341
#define MOTION_ERROR_CIRCULAR_MOVE_ACC_ERROR_TYPE				0x342
#define MOTION_ERROR_CIRCULAR_MOVE_DEC_ERROR_TYPE				0x343



#define MOTION_ERROR_CANNOT_MODIFY_ORGOFFSET_WHILE_ENABLED_TYPE			0x500
#define MOTION_ERROR_INPUT_AXIS_NUMBER_ERROR_TYPE							0x510
#define MOTION_ERROR_CANNOT_MODIFY_PUMA_WHILE_ENABLED_TYPE					0x520
#define MOTION_ERROR_CANNOT_MODIFY_TEACHV_WHILE_ENABLED_TYPE				0x530
#define MOTION_ERROR_CANNOT_MODIFY_MAX_LINEARV_WHILE_ENABLED_TYPE			0x540
#define MOTION_ERROR_CANNOT_MODIFY_MAX_LINEARACC_WHILE_ENABLED_TYPE		0x550
#define MOTION_ERROR_CANNOT_MODIFY_MAX_ROTATEV_WHILE_ENABLED_TYPE		0x560
#define MOTION_ERROR_CANNOT_MODIFY_MAX_ROTATEACC_WHILE_ENABLED_TYPE		0x570

#define MOTION_ERROR_CANNOT_MODIFY_SOFT_LIMIT_WHILE_ENABLED_TYPE			0x580
#define MOTION_ERROR_CANNOT_MODIFY_JOINT_VELOCITY_WHILE_ENABLED_TYPE		0x590
#define MOTION_ERROR_CANNOT_MODIFY_JOINT_ACC_WHILE_ENABLED_TYPE			0x600
#define MOTION_ERROR_CANNOT_MODIFY_RATIO_WHILE_ENABLED_TYPE				0x610

#define MOTION_ERROR_USR_CALIBARATION_FAILED_TYPE								0x620
#define MOTION_ERROR_TOOL_CALIBARATION_FAILED_TYPE							0x630
#define MOTION_ERROR_MOTION_ENABLE_FAILED_TYPE								0x640
#define MOTION_ERROR_CANNOT_ACCESS_SERVO_FAILED_TYPE							0x650

#define MOTION_ERROR_MOTION_RESET_FAILED_TYPE									0x660
#define MOTION_ERROR_CANNOT_INIT_SERVO_FAILED_TYPE							0x670
#define MOTION_ERROR_CYCLE_TIME_ERROR_TYPE										0x680
#define MOTION_ERROR_CANNOT_CREAT_TP_TYPE										0x690


#endif
