#ifndef MOTIONPARAMETERTYPE_H
#define MOTIONPARAMETERTYPE_H

#define	PUMA_A_TYPE										10
#define	TEACH_LINEAR_MOVE_MAX_VELOCITY_TYPE			20
#define	PLAY_LINEAR_MOVE_MAX_VELOCITY_TYPE				30
#define 	LINEAR_MOVE_ACC_TIME_TYPE						40
#define	ROTATE_MOVE_ACC_TIME_TYPE						50
#define	LINEAR_POSITIVE_LIMIT_TYPE						60
#define	LINEAR_NEGATIVE_LIMIT_TYPE						70
#define	JOINT_POSITIVE_LIMIT_TYPE							80
#define	JOINT_NEGATIVE_LIMIT_TYPE						90
#define	JOINTMOVE_MAX_VELOCITY_TYPE						100
#define	MECHANICAL_TRANSMISSION_RATIO_TYPE				110
#define	SERVO_PULSE_PER_ROUND_TYPE						120
#define	SERVO_MAX_VELOCITY_TYPE							130
#define	ENCODER_ORIGIN_OFFSET_TYPE						140
			

#endif
